config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  namespace :account do
    resources :posts do
      member do
        post :set_private
        post :set_public
        post :set_model
        post :quit_set_model
        post :quit_like
      end
      collection do
        get :select_model_new
        get :like_posts_index
      end
    end
    resources :categories
  end

  post 'upload' => "photos#upload"

  namespace :foreground do
    resources :posts do
      member do
        post :like
        post :quit_like
      end
      resources :comments
    end

    resources :users
  end
end

app/models/post.rb
class Post < ApplicationRecord

  ##校验
  validates :title, presence: true

  ##关联
  belongs_to :user

  has_many :comments
  #文章模版自连接结构
  has_many :children_posts, class_name: 'Post',
           foreign_key: 'post_model_id'
  belongs_to :post_model, class_name: 'Post',
             optional: true
  #post和category的多对多关联
  has_many :post_category_relationships
  has_many :categories, :through => :post_category_relationships
  #用户收藏文章的多对多关联
  has_many :likes, :dependent => :destroy
  has_many :liked_users, :through => :likes, source:  :user

  ##scope方法
  scope :is_private, -> {where(set_is_private: true)}
  scope :is_public, -> {where(set_is_private: false)}

  scope :is_model, -> {where(set_is_model: true)}
  scope :is_not_model, -> {where(set_is_model: false)}

  ##回调
  # 使用模版写文章新增回调
  before_save :add_post_content, on: :create

  ##公有方法
  def find_like(user)
    self.likes.where( :user_id => user.id ).first
  end

  ##私有方法
  private

  def add_post_content
    self.content = self.post_model.content if (self.post_model && !self.content)
  end

end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.posts.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      if @post.post_model
        redirect_to edit_account_post_path(@post)
      else
        redirect_to account_posts_path
      end
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "post updated"
      redirect_to account_posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:alert] = "post deleted"
    redirect_back(fallback_location: root_path)
  end

  def set_private
    @post = Post.find(params[:id])
    @post.set_is_private = true
    @post.save
    redirect_back(fallback_location: root_path)
  end

  def set_public
    @post = Post.find(params[:id])
    @post.set_is_private = false
    @post.save
    redirect_back(fallback_location: root_path)
  end

  def set_model
    @post = Post.find(params[:id])
    @post.set_is_model = true
    @post.save
    redirect_back(fallback_location: root_path)
  end

  def quit_set_model
    @post = Post.find(params[:id])
    @post.set_is_model = false
    @post.save
    redirect_back(fallback_location: root_path)
  end

  def select_model_new
    @post = Post.new
    @my_post_models = current_user.posts.is_model
  end

  def like_posts_index
    @posts = current_user.liked_posts.order("created_at DESC")
  end

  def quit_like
    @post = Post.find(params[:id])
    like = @post.find_like(current_user)
    like.destroy

    redirect_back(fallback_location: root_path)
  end



  private

  def post_params
    params.require(:post).permit(:title, :content, :set_is_private, :set_is_model,
                                 :post_model_id, :category_ids => [])
  end
end

app/controllers/foreground/comments_controller.rb
class Foreground::CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user
    @comment.save

    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit( :content)
  end

end

app/controllers/foreground/posts_controller.rb
class Foreground::PostsController < ApplicationController

  def index
    @posts = Post.is_public.order("created_at DESC")
  end

  def show
    @post = Post.find(params[:id])

    @comment = Comment.new
    @comments = @post.comments.order("created_at DESC")
  end

  def like
    @post = Post.find(params[:id])
    unless @post.find_like(current_user)  # 如果已经按讚过了，就略过不再新增
      Like.create( :user => current_user, :post => @post)
    end

    redirect_back(fallback_location: root_path)
  end

  def quit_like
    @post = Post.find(params[:id])
    like = @post.find_like(current_user)
    like.destroy

    redirect_back(fallback_location: root_path)
  end

end

app/controllers/foreground/users_controller.rb
class Foreground::UsersController < ApplicationController

  def index
    @users = User.all.order("created_at DESC")
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/foreground/comments_helper.rb
module Foreground::CommentsHelper
end

app/helpers/foreground/posts_helper.rb
module Foreground::PostsHelper
end

app/helpers/foreground/users_helper.rb
module Foreground::UsersHelper
end

app/views/foreground/posts/index.html.erb
<div class="col-md-12">
  <table class="table table-hover">
    <thead>
    <td>发表时间</td>
    <td>文章题目</td>
    <td>作者</td>
    </thead>
    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <%= post.created_at.strftime("%Y-%b-%d   %H:%M") %>
        </td>
        <td>
          <%= link_to(post.title, foreground_post_path(post)) %>
        </td>
        <td>
          <%= post.user.email %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/foreground/posts/show.html.erb
<div class="col-md-12">
  <div class="post">

    <%= link_to("回到文章列表", foreground_posts_path, class: "btn btn-primary") %>

  </div>

  <div>
    <h3>
      <%= @post.title %>
      <% if current_user # 有登入才可以按讚 %>
        <% if @post.find_like(current_user) %>
          <%= link_to "取消收藏", quit_like_foreground_post_path(@post), :method => :post, :class => "btn btn-warning" %>
        <% else %>
          <%= link_to "收藏文章", like_foreground_post_path(@post), :method => :post, :class => "btn btn-primary" %>
        <% end %>
      <% end %>
    </h3>
    <h4>
      <span class="label label-info">发表时间：<%= @post.created_at.strftime("%Y-%b-%d   %H:%M") %></span>
      <span class="label label-info">作者：<%= @post.user.email %></span>
    </h4>
    <p>
      <%= simple_format(@post.content) %>
    </p>

  </div>

  <hr>
  <h4>评论区</h4>
  <div>
    <%= simple_form_for [:foreground, @post, Comment.new] do |f| %>

      <div class="group">
        <%= f.input :content, label: "内容" %>
      </div>

      <%= f.submit "提交", :class => "btn btn-primary", data: { disable_with: "Submitting..." } %>

    <% end %>
  </div>
  <div>
    <h5>评论列表</h5>
    <table class="table table-hover">
      <thead>
      <td>评论人</td>
      <td>评论时间</td>
      <td>内容</td>
      </thead>
      <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td>
            <%= comment.user.email %>
          </td>
          <td>
            <%= comment.created_at.strftime("%Y-%b-%d   %H:%M") %>
          </td>
          <td>
            <%= comment.content %>
          </td>
        </tr>
      <% end %>
      </tbody>

    </table>
  </div>
</div>