config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  namespace :account do
    resources :posts do
      member do
        post :set_private
        post :set_public
        post :set_model
        post :quit_set_model
        post :quit_like
      end
      collection do
        get :select_model_new
        get :like_posts_index
      end
    end
    resources :categories
  end

  post 'upload' => "photos#upload"

  namespace :foreground do
    resources :posts do
      member do
        post :like
        post :quit_like
      end
      resources :comments
    end

    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ##关联
  has_many :posts, :dependent => :destroy
  has_many :categories
  has_many :comments
  #用户收藏文章的多对多关联
  has_many :likes
  has_many :liked_posts, :through => :likes, :source => :post



end

app/controllers/foreground/comments_controller.rb
class Foreground::CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user
    @comment.save

    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit( :content)
  end

end

app/controllers/foreground/posts_controller.rb
class Foreground::PostsController < ApplicationController

  def index
    @posts = Post.is_public.order("created_at DESC")
  end

  def show
    @post = Post.find(params[:id])

    @comment = Comment.new
    @comments = @post.comments.order("created_at DESC")
  end

  def like
    @post = Post.find(params[:id])
    unless @post.find_like(current_user)  # 如果已经按讚过了，就略过不再新增
      Like.create( :user => current_user, :post => @post)
    end

    redirect_back(fallback_location: root_path)
  end

  def quit_like
    @post = Post.find(params[:id])
    like = @post.find_like(current_user)
    like.destroy

    redirect_back(fallback_location: root_path)
  end

end

app/controllers/foreground/users_controller.rb
class Foreground::UsersController < ApplicationController

  def index
    @users = User.all.order("created_at DESC")
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/foreground/comments_helper.rb
module Foreground::CommentsHelper
end

app/helpers/foreground/posts_helper.rb
module Foreground::PostsHelper
end

app/helpers/foreground/users_helper.rb
module Foreground::UsersHelper
end

app/views/foreground/users/index.html.erb
<div class="col-md-12">
  <table class="table table-hover">
    <thead>
    <td>注册时间</td>
    <td>作者</td>
    <td>文章量</td>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= user.created_at.strftime("%Y-%b-%d   %H:%M") %>
        </td>
        <td>
          <%= link_to(user.email, foreground_user_path(user)) %>
        </td>
        <td>
          <%= user.posts.count %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/foreground/users/show.html.erb
<div class="col-md-12">
  <div class="post">

    <%= link_to("回到作者列表", foreground_users_path, class: "btn btn-primary") %>

  </div>

  <div>
    <h3>
      作者邮箱：<%= @user.email %>
    </h3>
    <h4>
      作者注册时间：<%= @user.created_at.strftime("%Y-%b-%d   %H:%M") %>
    </h4>
    <h4>
      作者文章数量：<%= @user.posts.count %> ;公开文章：<%= @user.posts.is_public.count %>
    </h4>


  </div>
</div>