config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  namespace :account do
    resources :posts do
      member do
        post :set_private
        post :set_public
        post :set_model
        post :quit_set_model
        post :quit_like
      end
      collection do
        get :select_model_new
        get :like_posts_index
      end
    end
    resources :categories
  end

  post 'upload' => "photos#upload"

  namespace :foreground do
    resources :posts do
      member do
        post :like
        post :quit_like
      end
      resources :comments
    end

    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  ##校验
  validates :name, presence: true

  ##关联
  belongs_to :user
  #post和category的多对多关联
  has_many :post_category_relationships
  has_many :posts, :through => :post_category_relationships
end

app/models/comment.rb
class Comment < ApplicationRecord

  ##校验
  validates :content, presence: true

  ##关联
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord

  ##关联
  belongs_to :user
  belongs_to :post
end

app/models/photo.rb
class Photo < ApplicationRecord

  ##校验
  validates :user_id, presence: true
  validates :image, presence: true
  ##上传插件
  mount_uploader :image, PhotoUploader

end

app/models/post.rb
class Post < ApplicationRecord

  ##校验
  validates :title, presence: true

  ##关联
  belongs_to :user

  has_many :comments
  #文章模版自连接结构
  has_many :children_posts, class_name: 'Post',
           foreign_key: 'post_model_id'
  belongs_to :post_model, class_name: 'Post',
             optional: true
  #post和category的多对多关联
  has_many :post_category_relationships
  has_many :categories, :through => :post_category_relationships
  #用户收藏文章的多对多关联
  has_many :likes, :dependent => :destroy
  has_many :liked_users, :through => :likes, source:  :user

  ##scope方法
  scope :is_private, -> {where(set_is_private: true)}
  scope :is_public, -> {where(set_is_private: false)}

  scope :is_model, -> {where(set_is_model: true)}
  scope :is_not_model, -> {where(set_is_model: false)}

  ##回调
  # 使用模版写文章新增回调
  before_save :add_post_content, on: :create

  ##公有方法
  def find_like(user)
    self.likes.where( :user_id => user.id ).first
  end

  ##私有方法
  private

  def add_post_content
    self.content = self.post_model.content if (self.post_model && !self.content)
  end

end

app/models/post_category_relationship.rb
class PostCategoryRelationship < ApplicationRecord
  ##关联
  belongs_to :category
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ##关联
  has_many :posts, :dependent => :destroy
  has_many :categories
  has_many :comments
  #用户收藏文章的多对多关联
  has_many :likes
  has_many :liked_posts, :through => :likes, :source => :post



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  def upload
    @photo = Photo.new
    @photo.image = params[:upload_file]
    @photo.user_id = current_user.id
    if @photo.save
      render json: { :success=> true ,:file_path=> @photo.image.url}
    else
      render json: { :success=> false }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    flash[:notice] = "hello world!"
  end
end

app/helpers/account/categories_helper.rb
module Account::CategoriesHelper
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/foreground/comments_helper.rb
module Foreground::CommentsHelper
end

app/helpers/foreground/posts_helper.rb
module Foreground::PostsHelper
end

app/helpers/foreground/users_helper.rb
module Foreground::UsersHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">

  <p class="text-center">Copyright ©2020 Rails-example

    <br>Design by yourname

  </p>

</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">

  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->

    <div class="navbar-header">

      <a class="navbar-brand" href="/">rails-example</a>

    </div>



    <!-- Collect the nav links, forms, and other content for toggling -->

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to("个人文章", account_posts_path) %></li>
        <li><%= link_to("个人文章分类", account_categories_path) %></li>
        <li><%= link_to("文章广场", foreground_posts_path) %></li>
        <li><%= link_to("我的收藏", like_posts_index_account_posts_path) %></li>
        <li><%= link_to("作者列表", foreground_users_path) %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">

        <% if !current_user %>
          <li><%= link_to("注册", new_user_registration_path) %> </li>
          <li><%= link_to(content_tag(:i, '登入', class: 'fa fa-sign-in'), new_user_session_path) %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to(content_tag(:i, '登出', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %> </li>
            </ul>
          </li>
        <% end %>

      </ul>

    </div>

    <!-- /.navbar-collapse -->

  </div>

  <!-- /.container-fluid -->

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsExample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">

    <%= render "common/navbar" %>
    <%= render "common/flashes" %>
    <%= yield %>

  </div>

  <%= render "common/footer" %>
  </body>
</html>